### ISSUE TITLE
Broken after updating to 2023.5.2

### ISSUE THREAD

**Issue by Verpz** [gunkutzeybek/hikaxpro_hacs#13]
My integration was working perfectly and now I am getting this error after updating to 2023.5.2

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/__init__.py:58
Integration: hikvision_axpro
First occurred: 11:02:11 (2 occurrences)
Last logged: 11:05:53

Error setting up entry Hikvision_axpro_192.168.1.158 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 58, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by rampionx** [comment]
Hi Verpz,
I got the same problem since the last update. After searching the web i found a fork of this projet:
https://github.com/petrleocompel/hikaxpro_hacs
I installed it and then it works with more options.
